#!/bin/bash
sudo apt-get remove skype skype-bin
sudo wget http://download.skype.com/linux/skype-ubuntu-precise_4.2.0.11-1_i386.deb
sudo dpkg -i skype-ubuntu*.deb; sudo apt-get -f install
sudo apt-get install libasound2-plugins:i386
sudo apt-get install sni-qt sni-qt:i386
skype &
rm -f skype-ubuntu-precise_4.2.0.11-1_i386.deb